service: aws-node-project

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  myService:
    handler: index.handler
    events:
      - sns:
          arn: !Ref SuperTopic
          topicName: MyCustomTopic

constructs:
  myQueue:
    type: queue
    worker:
      handler: index.handler

plugins:
  - serverless-lift
  - ./serverless-plugin-canary-deployments

resources:
  Resources:
    SuperTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: MyCustomTopic
